version: '3.8' 
 
services: 
  mysql: 
    image: mysql:8 
    container_name: mysql-container02 
    environment: 
      MYSQL_ROOT_PASSWORD: admin1234 
      MYSQL_DATABASE: spring_lab06
    ports: 
      - "3306:3306" 
    volumes: 
      - mysql-data:/var/lib/mysql 
    networks: 
      - spring-net 
 
  springlab06: 
    build: . 
    image: mylab07 #이미지 이름 명시
    container_name: springlab07-app 
    ports: 
      - "8080:8080" 
    depends_on: 
      - mysql 
    networks: 
      - spring-net 
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/spring_lab06?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin1234 
 
volumes: 
  mysql-data: 
 
networks: 
  spring-net: