
-- Q1. 대출 횟수가 20회 이상인 도서들의 식별번호, isbn, 제목, 대출횟수 정보를 조회하세요.
SELECT BK_IDX, ISBN, TITLE, RENT_CNT FROM BOOK WHERE RENT_CNT >= 20;

-- Q2. 등록일이 2020년 6월 20일 이후인 도서의 식별번호, isbn, 제목, 등록일자 정보를 조회하세요.
SELECT BK_IDX, ISBN, TITLE, REG_DATE FROM BOOK WHERE REG_DATE > '2020-06-20';

-- Q3. 카테고리가 'B001'이고 대출 횟수가 8회인 도서의 정보를 조회하세요.
SELECT BK_IDX, ISBN, TITLE, RENT_CNT FROM BOOK WHERE CATEGORY = 'B001' AND RENT_CNT = 8;

-- Q4. 저자가 '혜민'인 도서 정보를 조회하세요.
SELECT bk_idx, isbn, title, author
FROM book
WHERE AUTHOR LIKE '%혜민%';

-- Q5. 도서 제목에 '소설'이 포함된 도서 제목을 조회하세요.
SELECT TITLE FROM BOOK WHERE TITLE LIKE '%소설%';

-- Q6. 등록일이 2020-04-15 이전이고 대출횟수 10회 이하 도서 조회
SELECT BK_IDX, ISBN, TITLE, AUTHOR, REG_DATE, RENT_CNT 
FROM BOOK WHERE REG_DATE < '2020-04-15' AND RENT_CNT <= 10;

-- Q7. 도서 제목이 '나는'으로 시작하는 도서 조회
SELECT BK_IDX, ISBN, TITLE, AUTHOR, REG_DATE, RENT_CNT 
FROM BOOK WHERE TITLE LIKE '나는%';

-- Q8. 도서 카테고리별 평균 대출건수와 총 대출건수 조회
SELECT CATEGORY, AVG(RENT_CNT) AS "평균 대출 건수", 
SUM(RENT_CNT) AS "총 대출 건수"
FROM BOOK 
GROUP BY CATEGORY;

-- Q9. 대출 횟수 많은 TOP 5 도서 조회
SELECT BK_IDX, ISBN, TITLE, AUTHOR, REG_DATE, RENT_CNT 
 FROM BOOK ORDER BY RENT_CNT DESC LIMIT 5;

-- Q10. 카테고리가 'B002'인 도서를 등록일 내림차순으로 조회
SELECT BK_IDX, ISBN, CATEGORY, TITLE, AUTHOR, REG_DATE FROM BOOK 
WHERE CATEGORY = 'B002' ORDER BY REG_DATE DESC;

-- Q11. ROLE_USER 회원을 이름 오름차순 조회
SELECT * FROM MEMBER WHERE GRADE = 'ROLE_USER' ORDER BY USER_ID;

-- Q12. ROLE_ADMIN이면서 탈퇴(IS_LEAVE)하지 않은 회원 조회
SELECT * FROM MEMBER WHERE GRADE = 'ROLE_ADMIN' AND IS_LEAVE = 0;

-- Q13. 등급 별 사용자 수 조회
SELECT GRADE, COUNT(*) AS CNT FROM MEMBER GROUP BY GRADE;

-- Q14. ROLE_USER이면서 전화번호가 9로 끝나는 회원 조회
SELECT * FROM MEMBER WHERE GRADE = 'ROLE_USER' AND TELL LIKE '%9';

-- Q15. 탈퇴하지 않은 ROLE_ADMIN 회원 이메일 조회 (알파벳 순)
SELECT EMAIL FROM MEMBER WHERE GRADE = 'ROLE_ADMIN' AND IS_LEAVE = 0 ORDER BY EMAIL;

-- Q16. ROLE_USER이고 탈퇴하지 않았으며, 전화번호 4번째 숫자 2, ID가 E로 시작하는 회원
SELECT * FROM MEMBER WHERE GRADE = 'ROLE_USER' AND IS_LEAVE = 0 
AND SUBSTR(TELL,5,1)='2' AND USER_ID LIKE 'E%';

-- Q17. 게시글에서 '철학' 포함된 글 조회
SELECT * FROM BOARD WHERE TITLE LIKE '%철학%' OR CONTENT LIKE '%철학%';

-- Q18. 게시글 뷰 수 상위 10개 조회
SELECT * FROM BOARD ORDER BY VIEW_CNT DESC LIMIT 10;

-- Q19. 조회수 700 이상이고 작성자가 Socrates인 글 조회
SELECT * FROM BOARD WHERE VIEW_CNT >= 700 AND USER_ID = 'Socrates';

-- Q20. 도서의 대분류 표시 (문학/전문서적)
SELECT BK_IDX, TITLE, AUTHOR,
CASE 
    WHEN CATEGORY LIKE 'B0%' THEN '문학'
    WHEN CATEGORY LIKE 'B1%' THEN '전문서적'
END AS 대분류
FROM BOOK;

-- Q21. 대출상태가 'RE01'인 대출도서 조회
SELECT * FROM RENT_BOOK WHERE STATE = 'RE01';

-- Q22. 대출 도서가 2권 이상인 대출건 제목 조회
SELECT TITLE FROM RENT_MASTER WHERE RENT_BOOK_CNT >= 2;

-- Q23. 2020-06-25 ~ 2020-06-30 입고 도서 조회
SELECT BK_IDX, ISBN, TITLE, REG_DATE FROM BOOK WHERE REG_DATE BETWEEN '2020-06-25' AND '2020-06-30';

-- Q24. 2023년 12월에 탈퇴한 사용자 조회
SELECT M.USER_ID, M.EMAIL, M.GRADE 
FROM MEMBER M 
JOIN MEMBER_INFO MI ON M.USER_ID = MI.USER_ID 
WHERE MI.LEAVE_DATE BETWEEN '2023-12-01' AND '2023-12-31';
