apiVersion: v1
kind: Pod #파드 상태
metadata:
  name: q1-emptydir-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo hello > /shared/hello.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /shared
          name: shared-volume
  volumes:
    - name: shared-volume
      emptyDir: {}
