apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: q3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: q3-pvc-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo persistent > /data/persistent.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: pvc-volume
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: q3-pvc
