apiVersion: v1
kind: Pod
metadata:
  name: q4-nfs-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls /mnt && sleep 3600"]
    volumeMounts:
    - mountPath: /mnt
      name: nfs-volume
  volumes:
  - name: nfs-volume
    nfs:
      server: 192.168.1.100  # Replace with actual NFS server IP
      path: /exports
