apiVersion: v1
kind: ConfigMap
metadata:
  name: q5-html-config
data:
  index.html: "<h1>Hello ConfigMap</h1>"
---
apiVersion: v1
kind: Pod
metadata:
  name: q5-configmap-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat /etc/html/index.html && sleep 3600"]
    volumeMounts:
    - mountPath: /etc/html
      name: html-volume
  volumes:
  - name: html-volume
    configMap:
      name: q5-html-config
      items:
      - key: index.html
        path: index.html
