apiVersion: v1
kind: Secret
metadata:
  name: q6-secret
type: Opaque
data:
  PASSWORD: YWRtaW4xMjM=  # base64 for "admin123"
---
apiVersion: v1
kind: Pod
metadata:
  name: q6-secret-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo PASSWORD=$PASSWORD && sleep 3600"]
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: q6-secret
          key: PASSWORD
